# Generated by Django 2.2.4 on 2019-08-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='numero_documento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='pacientes',
            unique_together={('tipo_documento', 'numero_documento')},
        ),
    ]
